In [1]:
import geopandas as gpd

In [3]:
gdf = gpd.read_parquet("../../data/processed/nsw_addressing/addresspoint_all.parquet")

In [4]:
print(len(gdf))
print(gdf.crs)
print(gdf.columns)
gdf.head()

4225113
{"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "GeographicCRS", "name": "WGS 84", "datum_ensemble": {"name": "World Geodetic System 1984 ensemble", "members": [{"name": "World Geodetic System 1984 (Transit)"}, {"name": "World Geodetic System 1984 (G730)"}, {"name": "World Geodetic System 1984 (G873)"}, {"name": "World Geodetic System 1984 (G1150)"}, {"name": "World Geodetic System 1984 (G1674)"}, {"name": "World Geodetic System 1984 (G1762)"}, {"name": "World Geodetic System 1984 (G2139)"}, {"name": "World Geodetic System 1984 (G2296)"}], "ellipsoid": {"name": "WGS 84", "semi_major_axis": 6378137, "inverse_flattening": 298.257223563}, "accuracy": "2.0", "id": {"authority": "EPSG", "code": 6326}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "scope": "Horizontal component of 3D system.", "area": "World.", "bbox": {"south_latitude": -90, "west_longitude": -180, "north_latitude": 90, "east_longitude": 180}, "id": {"authority": "EPSG", "code": 4326}}
Index(['rid', 'createdate', 'gurasid', 'principaladdresssiteoid',
       'addressstringoid', 'addresspointtype', 'addresspointuncertainty',
       'containment', 'startdate', 'enddate', 'lastupdate', 'msoid',
       'centroidid', 'shapeuuid', 'changetype', 'processstate', 'urbanity',
       'address', 'housenumber', 'geometry'],
      dtype='object')

,rid,createdate,gurasid,principaladdresssiteoid,addressstringoid,addresspointtype,addresspointuncertainty,containment,startdate,enddate,lastupdate,msoid,centroidid,shapeuuid,changetype,processstate,urbanity,address,housenumber,geometry
0,1,1136937600000,3336983,2289443,3165028.0,1,NaN,1,1208534459000,32503680000000,1208534459669,3036974,None,9e2a72c3-1848-3b0e-879f-b9ad78942d90,I,None,U,15 ELLALONG STREET PELAW MAIN,15,POINT (151.48578 -32.82698)
1,2,1136937600000,3336984,2516981,3165130.0,1,NaN,1,1208534459000,32503680000000,1208534459669,3036975,None,844a4f98-110f-31e3-addb-49d0cb2a30ef,I,None,U,14 MILLFIELD STREET PELAW MAIN,14,POINT (151.48575 -32.82645)
2,3,1136937600000,3336986,2516985,3153733.0,1,NaN,1,1208534459000,32503680000000,1208534459669,3036977,None,b101e7be-5908-361c-8434-bd4e3ad35f96,I,None,U,84 BROWN STREET DUNGOG,84,POINT (151.74908 -32.40085)
3,4,1136937600000,3336988,2516987,3153364.0,1,NaN,1,1208534459000,32503680000000,1208534459669,3036979,None,153e1f60-05ba-3450-8d16-28e167e672d9,I,None,U,297 CESSNOCK ROAD ABERMAIN,297,POINT (151.42538 -32.81159)
4,5,1136937600000,3336990,2516989,3164934.0,1,NaN,1,1208534459000,32503680000000,1208534459669,3036981,None,706be1c6-6c39-3d11-81b4-74a743d8c886,I,None,U,35 MELBOURNE STREET ABERMAIN,35,POINT (151.42916 -32.80931)

In [6]:
# Null rate
gdf.isna().mean().sort_values(ascending=False)

processstate               1.000000
centroidid                 1.000000
addresspointuncertainty    0.999996
housenumber                0.032383
address                    0.000004
addressstringoid           0.000004
rid                        0.000000
msoid                      0.000000
urbanity                   0.000000
changetype                 0.000000
shapeuuid                  0.000000
lastupdate                 0.000000
createdate                 0.000000
enddate                    0.000000
startdate                  0.000000
containment                0.000000
addresspointtype           0.000000
principaladdresssiteoid    0.000000
gurasid                    0.000000
geometry                   0.000000
dtype: float64

In [7]:
# address / housenumber / urbanity distribution
gdf["urbanity"].value_counts(dropna=False)

urbanity
U    3498034
S     727079
Name: count, dtype: int64

In [8]:
# geometry bounds
gdf.total_bounds

array([141.00140751, -37.43368181, 159.08345272, -28.15848597])

In [9]:
gdf[["address", "housenumber", "urbanity"]].sample(10, random_state=42)

                                  address housenumber urbanity
2262872            GRINTON AVENUE ASHMONT        None        U
136524           58 VISTA AVENUE CATALINA          58        U
3400623         5/40 TRAIN STREET BROULEE        5/40        S
975625             13 BACH AVENUE EMERTON          13        U
1229084         12 GUILFOYLE PLACE CUDGEN          12        U
3506896  14 SPURFIELD ROAD MCLEANS RIDGES          14        S
2094798       1/43 THE TRONGATE GRANVILLE        1/43        U
1372500              39 MANNS ROAD NARARA          39        U
466580         4 CAROLINA CRESCENT MUDGEE           4        U
3991008           62 WADE STREET COOLAMON          62        S