In [1]:
import pandas as pd
from pathlib import Path

In [2]:
GTFS_DIR = Path("../../data/raw/transport/gtfs")

stops = pd.read_csv(GTFS_DIR / "stops.txt")
routes = pd.read_csv(GTFS_DIR / "routes.txt")
trips = pd.read_csv(GTFS_DIR / "trips.txt")
stop_times = pd.read_csv(GTFS_DIR / "stop_times.txt")

/var/folders/kc/4swzx7w979z6w9js5c61gt7h0000gn/T/ipykernel_96924/4023579398.py:3: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  stops = pd.read_csv(GTFS_DIR / "stops.txt")
/var/folders/kc/4swzx7w979z6w9js5c61gt7h0000gn/T/ipykernel_96924/4023579398.py:5: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  trips = pd.read_csv(GTFS_DIR / "trips.txt")
/var/folders/kc/4swzx7w979z6w9js5c61gt7h0000gn/T/ipykernel_96924/4023579398.py:6: DtypeWarning: Columns (0,3,5,10) have mixed types. Specify dtype option on import or set low_memory=False.
  stop_times = pd.read_csv(GTFS_DIR / "stop_times.txt")

In [3]:
print(stops.columns)
print(routes.columns)
print(trips.columns)
print(stop_times.columns)

Index(['stop_id', 'stop_code', 'stop_name', 'stop_lat', 'stop_lon',
       'location_type', 'parent_station', 'wheelchair_boarding', 'level_id',
       'platform_code'],
      dtype='object')
Index(['route_id', 'agency_id', 'route_short_name', 'route_long_name',
       'route_desc', 'route_type', 'route_color', 'route_text_color',
       'exact_times'],
      dtype='object')
Index(['route_id', 'service_id', 'trip_id', 'shape_id', 'trip_headsign',
       'direction_id', 'block_id', 'wheelchair_accessible', 'route_direction',
       'trip_note', 'bikes_allowed'],
      dtype='object')
Index(['trip_id', 'arrival_time', 'departure_time', 'stop_id', 'stop_sequence',
       'stop_headsign', 'pickup_type', 'drop_off_type', 'shape_dist_traveled',
       'timepoint', 'stop_note'],
      dtype='object')

In [4]:
stops.head()

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,level_id,platform_code
0,2000110,2000110.0,"Central Grand Concourse, Light Rail Trackwork",-33.882227,151.206342,NaN,200060,1.0,Level 1,NaN
1,2000112,2000112.0,"Central Station, Forecourt, Coach Bay 5",-33.882859,151.204720,NaN,200060,2.0,Level 1,NaN
2,2000115,2000115.0,"Central Station, Forecourt, Coach Bay 7",-33.882492,151.205166,NaN,200060,2.0,Level 1,NaN
3,2000124,2000124.0,"Central Station, Forecourt, Coach Bay 9",-33.882144,151.205603,NaN,200060,2.0,Level 1,NaN
4,2000132,2000132.0,"Central Station, Forecourt, Coach Bay 8",-33.882266,151.205447,NaN,200060,2.0,Level 1,NaN

In [5]:
routes["route_type"].value_counts(dropna=False)

route_type
712    8642
700    1147
204     159
205     136
714      72
106      27
4        24
2        17
900       6
401       1
Name: count, dtype: int64

In [6]:
rail_route_types = [2, 401]

rail_routes = routes[routes["route_type"].isin(rail_route_types)].copy()
print(len(rail_routes))
rail_routes[["route_id", "route_type"]].head()

18

          route_id  route_type
2332   2-BMT-sj2-1           2
2333   2-CCN-sj2-1           2
2334   2-SCO-sj2-1           2
2335  2-T1-N-sj2-1           2
2336  2-T1-W-sj2-1           2

In [7]:
rail_trips = trips[trips["route_id"].isin(rail_routes["route_id"])].copy()
print(len(rail_trips))
rail_trips[["route_id", "trip_id"]].head()

63810

          route_id                          trip_id
34029  2-BMT-sj2-1  G402.1452.112.128.D.10.89849624
34030  2-BMT-sj2-1    G402.1452.112.2.D.10.89848021
34031  2-BMT-sj2-1    G404.1452.112.2.D.10.89856689
34032  2-BMT-sj2-1    G412.1452.112.2.D.10.89855845
34033  2-BMT-sj2-1    G414.1452.112.2.D.10.89855255

In [8]:
rail_stop_times = stop_times[stop_times["trip_id"].isin(rail_trips["trip_id"])].copy()
print(len(rail_stop_times))
rail_stop_times[["trip_id", "stop_id"]].head()

1002804

                               trip_id  stop_id
1393452  101A.1450.109.48.T.8.89729913   207262
1393453  101A.1450.109.48.T.8.89729913   207191
1393454  101A.1450.109.48.T.8.89729913  2070141
1393455  101A.1450.109.48.T.8.89729913  2069131
1393456  101A.1450.109.48.T.8.89729913  2067141

In [9]:
rail_stop_ids = rail_stop_times["stop_id"].dropna().unique()
len(rail_stop_ids)

832

In [10]:
rail_stops = stops[stops["stop_id"].isin(rail_stop_ids)].copy()
print(len(rail_stops))
rail_stops.head()

90

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,level_id,platform_code
15,2000321,2000321.0,"Central Station, Platform 1",-33.883165,151.205523,NaN,200060,1.0,Level 1,1
18,2000324,2000324.0,"Central Station, Platform 4",-33.883317,151.205812,NaN,200060,1.0,Level 1,4
19,2000325,2000325.0,"Central Station, Platform 5",-33.883360,151.205879,NaN,200060,1.0,Level 1,5
20,2000326,2000326.0,"Central Station, Platform 6",-33.883418,151.206011,NaN,200060,1.0,Level 1,6
21,2000327,2000327.0,"Central Station, Platform 7",-33.883452,151.206067,NaN,200060,1.0,Level 1,7

In [11]:
rail_stops.columns

Index(['stop_id', 'stop_code', 'stop_name', 'stop_lat', 'stop_lon',
       'location_type', 'parent_station', 'wheelchair_boarding', 'level_id',
       'platform_code'],
      dtype='object')

In [12]:
if "location_type" in rail_stops.columns:
    print(rail_stops["location_type"].value_counts(dropna=False))

location_type
NaN    90
Name: count, dtype: int64

In [13]:
import geopandas as gpd

rail_stops_gdf = gpd.GeoDataFrame(
    rail_stops.copy(),
    geometry=gpd.points_from_xy(rail_stops["stop_lon"], rail_stops["stop_lat"]),
    crs="EPSG:4326"
)

rail_stops_gdf.head()

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,level_id,platform_code,geometry
15,2000321,2000321.0,"Central Station, Platform 1",-33.883165,151.205523,NaN,200060,1.0,Level 1,1,POINT (151.20552 -33.88316)
18,2000324,2000324.0,"Central Station, Platform 4",-33.883317,151.205812,NaN,200060,1.0,Level 1,4,POINT (151.20581 -33.88332)
19,2000325,2000325.0,"Central Station, Platform 5",-33.883360,151.205879,NaN,200060,1.0,Level 1,5,POINT (151.20588 -33.88336)
20,2000326,2000326.0,"Central Station, Platform 6",-33.883418,151.206011,NaN,200060,1.0,Level 1,6,POINT (151.20601 -33.88342)
21,2000327,2000327.0,"Central Station, Platform 7",-33.883452,151.206067,NaN,200060,1.0,Level 1,7,POINT (151.20607 -33.88345)

In [17]:
rail_stops_gdf.dtypes

stop_id                  object
stop_code               float64
stop_name                object
stop_lat                float64
stop_lon                float64
location_type           float64
parent_station           object
wheelchair_boarding     float64
level_id                 object
platform_code            object
geometry               geometry
dtype: object

In [18]:
obj_cols = rail_stops_gdf.select_dtypes(include=["object"]).columns
rail_stops_gdf[obj_cols] = rail_stops_gdf[obj_cols].astype("string")

In [21]:
obj_cols = rail_stops_gdf.select_dtypes(include=["object"]).columns
rail_stops_gdf[obj_cols] = rail_stops_gdf[obj_cols].astype("string")

In [22]:
rail_stops_gdf.to_parquet(
    "../../data/processed/transport/rail_metro_stations_raw.parquet",
    index=False
)